# -*- coding: utf-8 -*-
"""NLP_Lab1_StopWords.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nVLZik8-5lRlhodMK3d1J_54AuijMYpu
"""

import nltk
nltk.download('all')

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

stop_words = set(stopwords.words('english'))
sentence = "There has been a lots of developements in this feild"
tokens = nltk.word_tokenize(sentence)
filtered_sentence = [w for w in tokens if not w in stop_words]
print(filtered_sentence)

stop_words = set(stopwords.words('english'))
sentence = "There has been a lots of developements in this feild"
tokens = nltk.word_tokenize(sentence)
filtered_sentence = [w for w in tokens if not w in stop_words]
print(filtered_sentence)

stop_words

