# -*- coding: utf-8 -*-
"""NLP_LAB4_MinimumEditDistance.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WiM8Jnb_GcljB2YsUpl02rYteAzJLPWu
"""

def min_edit_distance(str1, str2):
    m=len(str1)
    n=len(str2)
    dp=[[0 for j in range(n+1)] for i in range(m+1)]
    for i in range(m+1):
        dp[i][0]=i
    for j in range(n+1):
        dp[0][j]=j
    for i in range(1, m+1):
        for j in range(1, n+1):
            if str1[i-1]==str2[j-1]:
                dp[i][j]=dp[i-1][j-1]
            else:
                dp[i][j]=1+min(dp[i-1][j], dp[i][j-1], 1+dp[i-1][j-1])#without 1
    return dp[m][n]

str1=input("Enter first string: ")
str2=input("Enter Second string: ")

med=min_edit_distance(str1, str2)
print(med)

