# -*- coding: utf-8 -*-
"""NLP_lab1_Lemmatization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hz3IT1jnyTuKAO49Ej89vHOan0iO-k_s
"""

import nltk
nltk.download('all')

import nltk
nltk.download('all')
paragraph = '''history history historical'''

#Lemmatization
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
sentence = nltk.sent_tokenize(paragraph)
lemmatizer = WordNetLemmatizer()
for i in range(len(sentence)):
    words = nltk.word_tokenize(sentence[i])
    words = [lemmatizer.lemmatize(j) for j in words if j not in set(stopwords.words('english'))]
sentence[i] =''.join(words)
print(words)

print(sentence)

paragraph

sentence

lemmatizer.lemmatize('historical')

lemmatizer.lemmatize('history')

lemmatizer.lemmatize('intelligent')

