# -*- coding: utf-8 -*-
"""NLP_lab1_Stemming.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1azO9pxMfOyesv30hxJa-hMLL7Amqrdj7
"""



import nltk
nltk.download('all')
paragraph = '''history historical'''

#stemming
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords
sentence = nltk.sent_tokenize(paragraph)
stemmer = PorterStemmer()
for i in range(len(sentence)):
    words = nltk.word_tokenize(sentence[i])
    words = [stemmer.stem(word) for word in words if word not in set(stopwords.words('english'))]
sentence[i] =''.join(words)
print(words)

