# -*- coding: utf-8 -*-
"""NLP_Lab3_NGramModel.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Nx31exz5D7RJ6eSU0xvV0ySiMD0tq6p7
"""

import random

def generate_text(input_string, n=2, length=10):
    # Split input string into a list of words
    words = input_string.split()

    # Create a dictionary to store n-grams and their frequency counts
    ngrams = {}
    for i in range(len(words) - n):
        gram = ' '.join(words[i:i+n])
        if gram not in ngrams:
            ngrams[gram] = []
        ngrams[gram].append(words[i+n])

    # Generate text by starting with a random n-gram and choosing the next word based on the frequency count
    current_gram = random.choice(list(ngrams.keys()))
    result = current_gram
    for i in range(length):
        if current_gram not in ngrams:
            break
        next_word = random.choice(ngrams[current_gram])
        result += ' ' + next_word
        current_gram = ' '.join(result.split()[-n:])

    return result

# Example usage
input_string = "The quick brown fox jumps over the lazy dog"
generated_text = generate_text(input_string, n=2, length=10)
print(generated_text)

