# -*- coding: utf-8 -*-
"""NLP_LAB3(2)_NGramModel.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EaqkOFr0ZeQ8tH5o74JFkbHPdfwWARIR
"""

import re
from nltk.util import ngrams
from collections import defaultdict
s = "Artificial Intelligence refers to the ability of the machines and computer programs to perform taks that typically involve human intelligence, such as learning ability , problem solving and decision making."
tokens= [token for token in s.split(" ")]
output = list(ngrams(tokens, 1))
print(output)
freq_dist = defaultdict(int)
for output in output:
  freq_dist[output] +=1

total_ngrams = sum(freq_dist.values())

prob_dist = {}
for output, freq in freq_dist.items():
  prob_dist[output] = freq/total_ngrams

for output, prob in prob_dist.items():
  print(output, prob)

