# -*- coding: utf-8 -*-
"""NLP_lab1_Tokenization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hpC3RUyGcnafF4mvnXrgRE8rmhLE_vTi
"""

import nltk
nltk.download('all')

import nltk
nltk.download('all')

paragraph = '''Be it exploration, production, transportation, or logistics; the energy
sector often encompasses projects that are high in cost.
Because of various external factors, such as the global economic
environment and political situations, the sector is also exposed to severe
price fluctuations.
For this reason, leading energy companies are increasingly turning
to data-driven solutions, creating significant inroads for data science
applications.
By using predictive models, data scientists enable energy companies to
cut costs, lower risks, reduce their downtime, and optimize investments
while enhancing equipment maintenance capabilities.'''

sentence = nltk.sent_tokenize(paragraph)
word = nltk.word_tokenize(paragraph)
print(word)

print(sentence)

