# -*- coding: utf-8 -*-
"""NLP_Lab9_PCFG.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g5vRGJB4GKsNAGWFrCB_LTSClY3aMhCf
"""

import nltk
from nltk.parse import pchart
from nltk import Nonterminal, Production, PCFG

grammar = PCFG.fromstring("""
  S -> NP VP[1.0]
  PP -> P NP[0.4]| P NP PP[0.6]
  NP -> Det N1[0.6]| Det N1 PP[0.4]
  VP -> V NP[0.7]| V NP PP[0.3]
  Det -> 'the'[0.5]|'a'[0.5]
  N1 -> 'dog'[0.1667]|'cat'[0.1667]|'bird'[0.1667]|'man'[0.1667]|'woman'[0.1667]|'mat'[0.1667]
  V ->'chased'[0.3]|'sat'[0.3]|'ate'[0.4]
  P -> 'on'[0.2]|'in'[0.3]|'by'[0.5]
  """)''

parser = pchart.InsideChartParser(grammar)
sentence = "the dog chased the cat on the mat".split()
for tree in parser.parse(sentence):
  print(tree)

tree.pretty_print()

