# -*- coding: utf-8 -*-
"""NLP_Lab2_BagOfWords.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nm0jPSzLRV4YlM2lzWOv9NuDE81PS678
"""

import nltk
nltk.download('punkt')
nltk.download('stopwords')

paragraph = '''Be it exploration, production, transportation, or logistics; the energy
sector often encompasses projects that are high in cost.
Because of various external factors, such as the global economic
environment and political situations, the sector is also exposed to severe
price fluctuations.
For this reason, leading energy companies are increasingly turning
to data-driven solutions, creating significant inroads for data science
applications.
By using predictive models, data scientists enable energy companies to
cut costs, lower risks, reduce their downtime, and optimize investments
while enhancing equipment maintenance capabilities.'''

import nltk
nltk.download('punkt')
nltk.download('stopwords')
import re

from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer

ps = PorterStemmer()
wordnet = WordNetLemmatizer()
sentences = nltk.sent_tokenize(paragraph)
corpus = []

for i in range(len(sentences)):
  review = re.sub('[^a-zA-Z]','', sentences[i])
  review = review.lower()
  review = review.split()
  review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
  review = ''.join(review)
  corpus.append(review)

print(len(sentences))
print(review)
print(corpus)

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 1500)
x = cv.fit_transform(corpus).toarray()
print(x)

